# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-harmony

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    The Harmony project
Version:    0.0
Release:    1
Group:      Qt/Qt
License:    BSD
URL:        https://github.com/SfietKonstantin/harmony
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-harmony.yaml
Requires:   nodejs
Requires:   openssl
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(libssl)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10
BuildRequires:  openssl
BuildRequires:  coffeescript

%description
An experiment about running a webapplication 
to expose phone information


%package runner
Summary:    Harmony runner
Group:      Qt/Qt
Requires:   %{name} = %{version}-%{release}

%description runner
A tester application to run the Node project


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5  \
    CONFIG+=harmonydebug

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
# >> files
# << files

%files runner
%defattr(-,root,root,-)
%{_bindir}/harmonyrunner
# >> files runner
# << files runner
